# Generated by Django 4.0 on 2024-02-14 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Good',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=25, verbose_name='название товара')),
                ('selling_price', models.FloatField(verbose_name='цена продажи')),
                ('purchase_price', models.FloatField(verbose_name='закупочная цена')),
                ('description', models.TextField(verbose_name='описание товара')),
                ('image', models.ImageField(upload_to='goods/', verbose_name='картинка товара')),
                ('quantity', models.IntegerField(verbose_name='кол-во товара')),
                ('sold_quantity', models.IntegerField(default=0, verbose_name='кол-во продано')),
                ('activity_flag', models.CharField(choices=[('a', 'Aктивный'), ('i', 'Стоп-лист')], default='i', max_length=1, verbose_name='флаг активности')),
            ],
            options={
                'verbose_name': 'товар',
                'verbose_name_plural': 'товары',
                'db_table': 'good',
            },
        ),
        migrations.CreateModel(
            name='GoodCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('good_num', models.PositiveIntegerField(default=1, verbose_name='кол-во')),
                ('payment_flag', models.CharField(choices=[('p', 'Оплачен'), ('n', 'Не оплачен')], default='n', max_length=1, verbose_name='статус оплаты')),
                ('good', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_store.good', verbose_name='товар')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user', verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'корзина',
                'verbose_name_plural': 'корзины',
                'db_table': 'good2cart',
            },
        ),
        migrations.CreateModel(
            name='GoodCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50, verbose_name='категория товара')),
            ],
            options={
                'verbose_name': 'категория',
                'verbose_name_plural': 'категории',
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='поставщик')),
                ('phone_number', models.CharField(max_length=11, verbose_name='телефон поставщика')),
                ('email', models.EmailField(max_length=50, verbose_name='почта')),
                ('contact_person', models.CharField(max_length=255, verbose_name='контактное лицо')),
                ('categories', models.ManyToManyField(to='app_store.GoodCategory', verbose_name='категории')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='дата заказа')),
                ('amount', models.FloatField(default=0, verbose_name='общая стоимость')),
                ('cart_good', models.ManyToManyField(to='app_store.GoodCart', verbose_name='товар из корзины')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user', verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'заказ',
                'verbose_name_plural': 'заказы',
                'db_table': 'order',
            },
        ),
        migrations.AddField(
            model_name='good',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_store.goodcategory', verbose_name='категория'),
        ),
        migrations.AddField(
            model_name='good',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_store.provider', verbose_name='поставщик'),
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth.user', verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
                'db_table': 'Employees',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birthday', models.DateField(verbose_name='birthdate')),
                ('phone', models.CharField(max_length=11)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth.user', verbose_name='покупатель')),
            ],
            options={
                'verbose_name': 'покупатель',
                'verbose_name_plural': 'покупатели',
                'db_table': 'Customers',
            },
        ),
    ]
