# Generated by Django 4.0 on 2024-02-27 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Good',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=25, verbose_name='название товара')),
                ('part_number', models.CharField(default='', max_length=10, verbose_name='артикул')),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='цена продажи')),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='закупочная цена')),
                ('description', models.TextField(verbose_name='описание товара')),
                ('image', models.ImageField(blank=True, null=True, upload_to='goods/', verbose_name='картинка товара')),
                ('quantity', models.IntegerField(default=0, verbose_name='кол-во товара')),
                ('sold_quantity', models.IntegerField(default=0, verbose_name='кол-во продано')),
                ('manufacturer', models.CharField(max_length=30, verbose_name='производитель')),
            ],
            options={
                'verbose_name': 'товар',
                'verbose_name_plural': 'товары',
                'db_table': 'good',
            },
        ),
        migrations.CreateModel(
            name='GoodCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50, verbose_name='категория товара')),
            ],
            options={
                'verbose_name': 'категория',
                'verbose_name_plural': 'категории',
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='поставщик')),
                ('phone_number', models.CharField(max_length=11, verbose_name='телефон поставщика')),
                ('email', models.EmailField(max_length=50, verbose_name='почта')),
                ('contact_person', models.CharField(max_length=255, verbose_name='контактное лицо')),
                ('categories', models.ManyToManyField(to='app_store.GoodCategory', verbose_name='категории')),
            ],
            options={
                'verbose_name': 'поставщик',
                'verbose_name_plural': 'поставщики',
                'db_table': 'providers',
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_date', models.DateTimeField(auto_now_add=True, verbose_name='дата продажи')),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='скидка (в процентах)')),
                ('payment_method', models.CharField(choices=[('наличные', 'наличные'), ('карта', 'карта')], default='наличные', max_length=50, verbose_name='способ оплаты')),
                ('final_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='итоговая стоимость')),
            ],
            options={
                'verbose_name': 'продажа',
                'verbose_name_plural': 'продажи',
                'db_table': 'sales',
            },
        ),
        migrations.CreateModel(
            name='Supply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supply_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'поставка',
                'verbose_name_plural': 'поставки',
                'db_table': 'supplies',
            },
        ),
        migrations.CreateModel(
            name='SupplyGood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('good', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_store.good')),
                ('supply', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_store.supply')),
            ],
        ),
        migrations.AddField(
            model_name='supply',
            name='goods',
            field=models.ManyToManyField(through='app_store.SupplyGood', to='app_store.Good'),
        ),
        migrations.AddField(
            model_name='supply',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_store.provider', verbose_name='поставщик'),
        ),
        migrations.CreateModel(
            name='SaleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='количество')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='цена')),
                ('good', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_store.good', verbose_name='товар')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sale_items', to='app_store.sale')),
            ],
            options={
                'verbose_name': 'проданный товар',
                'verbose_name_plural': 'проданные товары',
                'db_table': 'sold_goods',
            },
        ),
        migrations.AddField(
            model_name='sale',
            name='goods',
            field=models.ManyToManyField(through='app_store.SaleItem', to='app_store.Good'),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birthday', models.DateField(verbose_name='дата рождения')),
                ('phone', models.CharField(max_length=11)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth.user', verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'пользователь',
                'verbose_name_plural': 'пользователи',
                'db_table': 'profile',
            },
        ),
        migrations.AddField(
            model_name='good',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_store.goodcategory', verbose_name='категория'),
        ),
    ]
