# Generated by Django 4.0 on 2024-02-16 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoodCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50, verbose_name='категория товара')),
            ],
            options={
                'verbose_name': 'категория',
                'verbose_name_plural': 'категории',
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='поставщик')),
                ('phone_number', models.CharField(max_length=11, verbose_name='телефон поставщика')),
                ('email', models.EmailField(max_length=50, verbose_name='почта')),
                ('contact_person', models.CharField(max_length=255, verbose_name='контактное лицо')),
                ('categories', models.ManyToManyField(to='app_store.GoodCategory', verbose_name='категории')),
            ],
            options={
                'verbose_name': 'поставщик',
                'verbose_name_plural': 'поставщики',
                'db_table': 'providers',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birthday', models.DateField(verbose_name='дата рождения')),
                ('phone', models.CharField(max_length=11)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth.user', verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'пользователь',
                'verbose_name_plural': 'пользователи',
                'db_table': 'profile',
            },
        ),
        migrations.CreateModel(
            name='Good',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=25, verbose_name='название товара')),
                ('part_number', models.CharField(default='', max_length=10, verbose_name='артикул')),
                ('selling_price', models.FloatField(verbose_name='цена продажи')),
                ('purchase_price', models.FloatField(verbose_name='закупочная цена')),
                ('description', models.TextField(verbose_name='описание товара')),
                ('image', models.ImageField(blank=True, null=True, upload_to='goods/', verbose_name='картинка товара')),
                ('quantity', models.IntegerField(verbose_name='кол-во товара')),
                ('sold_quantity', models.IntegerField(default=0, verbose_name='кол-во продано')),
                ('activity_flag', models.CharField(choices=[('a', 'Aктивный'), ('i', 'Стоп-лист')], default='i', max_length=1, verbose_name='флаг активности')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_store.goodcategory', verbose_name='категория')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_store.provider', verbose_name='поставщик')),
            ],
            options={
                'verbose_name': 'товар',
                'verbose_name_plural': 'товары',
                'db_table': 'good',
            },
        ),
    ]
