# Generated by Django 4.0 on 2024-02-27 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_store', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='goods',
        ),
    ]
