# Generated by Django 4.0 on 2024-02-16 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_store', '0002_remove_profile_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
    ]
