# Generated by Django 4.0 on 2024-02-14 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_store', '0002_alter_provider_options_alter_provider_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='good',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='goods/', verbose_name='картинка товара'),
        ),
    ]
