# Generated by Django 4.0 on 2024-02-19 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_store', '0003_remove_profile_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='good',
            name='quantity',
            field=models.IntegerField(null=True, verbose_name='кол-во товара'),
        ),
    ]
