# Generated by Django 4.0 on 2024-02-27 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_store', '0003_remove_saleitem_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='goods',
            field=models.ManyToManyField(through='app_store.SaleItem', to='app_store.Good'),
        ),
    ]
