# Generated by Django 4.0 on 2024-02-23 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_store', '0004_alter_good_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supply_date', models.DateTimeField(auto_now_add=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_store.provider')),
            ],
            options={
                'verbose_name': 'поставка',
                'verbose_name_plural': 'поставки',
                'db_table': 'supplies',
            },
        ),
        migrations.AlterField(
            model_name='good',
            name='quantity',
            field=models.IntegerField(default=1, verbose_name='кол-во товара'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='SupplyItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('good', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_store.good')),
                ('supply', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='app_store.supply')),
            ],
        ),
    ]
