# Generated by Django 4.0 on 2024-03-02 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_store', '0005_alter_saleitem_sale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='payment_method',
            field=models.CharField(choices=[('Наличные', 'Наличные'), ('Карта', 'Карта')], default='Наличные', max_length=50, verbose_name='способ оплаты'),
        ),
    ]
