# Generated by Django 4.0 on 2024-02-23 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_store', '0005_supply_alter_good_quantity_supplyitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='good',
            name='quantity',
            field=models.IntegerField(default=0, verbose_name='кол-во товара'),
        ),
    ]
