# Generated by Django 4.0 on 2024-02-25 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_store', '0006_alter_good_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='good',
            name='activity_flag',
        ),
        migrations.RemoveField(
            model_name='supply',
            name='provider',
        ),
        migrations.AddField(
            model_name='supply',
            name='good',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app_store.good'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supply',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='SupplyItem',
        ),
    ]
