# Generated by Django 4.0 on 2024-03-04 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_store', '0006_alter_sale_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='position',
            field=models.CharField(default=1, max_length=30, verbose_name='должность'),
            preserve_default=False,
        ),
    ]
