# Generated by Django 4.0 on 2024-02-25 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_store', '0007_remove_good_activity_flag_remove_supply_provider_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_date', models.DateTimeField(auto_now_add=True, verbose_name='дата продажи')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_store.profile', verbose_name='сотрудник')),
            ],
            options={
                'verbose_name': 'продажа',
                'verbose_name_plural': 'продажи',
                'db_table': 'sales',
            },
        ),
        migrations.CreateModel(
            name='SoldGood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='количество')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='общая цена')),
                ('good', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_store.good', verbose_name='товар')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sold_goods', to='app_store.sale')),
            ],
            options={
                'verbose_name': 'проданный товар',
                'verbose_name_plural': 'проданные товары',
                'db_table': 'sold_goods',
            },
        ),
    ]
