# Generated by Django 4.0 on 2024-03-15 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_store', '0007_profile_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='good',
            name='name',
            field=models.CharField(db_index=True, max_length=30, verbose_name='название товара'),
        ),
    ]
