# Generated by Django 4.0 on 2024-02-25 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_store', '0008_sale_soldgood'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='soldgood',
            name='total_price',
        ),
        migrations.AddField(
            model_name='sale',
            name='discount',
            field=models.IntegerField(default=0, verbose_name='скидка (в процентах)'),
        ),
        migrations.AddField(
            model_name='sale',
            name='final_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='финальная стоимость'),
        ),
        migrations.AddField(
            model_name='sale',
            name='payment_method',
            field=models.CharField(choices=[('наличные', 'наличные'), ('карта', 'карта')], default='наличные', max_length=50, verbose_name='способ оплаты'),
        ),
        migrations.AddField(
            model_name='soldgood',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='цена'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='good',
            name='purchase_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='закупочная цена'),
        ),
        migrations.AlterField(
            model_name='good',
            name='selling_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='цена продажи'),
        ),
    ]
