# Generated by Django 4.0 on 2024-02-26 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_store', '0009_remove_soldgood_total_price_sale_discount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplyGood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('good', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_store.good')),
            ],
        ),
        migrations.RemoveField(
            model_name='supply',
            name='good',
        ),
        migrations.RemoveField(
            model_name='supply',
            name='quantity',
        ),
        migrations.AddField(
            model_name='supply',
            name='goods',
            field=models.ManyToManyField(through='app_store.SupplyGood', to='app_store.Good'),
        ),
        migrations.AddField(
            model_name='supply',
            name='provider',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app_store.provider', verbose_name='поставщик'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supplygood',
            name='supply',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_store.supply'),
        ),
    ]
