# Generated by Django 4.0 on 2024-02-26 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_store', '0010_supplygood_remove_supply_good_remove_supply_quantity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='good',
            name='provider',
        ),
        migrations.AddField(
            model_name='good',
            name='manufacturer',
            field=models.CharField(default=1, max_length=30, verbose_name='производитель'),
            preserve_default=False,
        ),
    ]
