# Generated by Django 4.0 on 2024-02-26 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_store', '0011_remove_good_provider_good_manufacturer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='final_price',
        ),
        migrations.AddField(
            model_name='sale',
            name='final_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='итоговая стоимость'),
        ),
        migrations.AddField(
            model_name='sale',
            name='goods',
            field=models.ManyToManyField(through='app_store.SoldGood', to='app_store.Good'),
        ),
    ]
