# Generated by Django 4.0 on 2024-02-27 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_store', '0012_remove_sale_final_price_sale_final_cost_sale_goods'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='количество')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='цена')),
                ('good', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_store.good', verbose_name='товар')),
            ],
            options={
                'verbose_name': 'проданный товар',
                'verbose_name_plural': 'проданные товары',
                'db_table': 'sold_goods',
            },
        ),
        migrations.RemoveField(
            model_name='sale',
            name='user',
        ),
        migrations.AlterField(
            model_name='sale',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='скидка (в процентах)'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='goods',
            field=models.ManyToManyField(through='app_store.SaleItem', to='app_store.Good'),
        ),
        migrations.DeleteModel(
            name='SoldGood',
        ),
        migrations.AddField(
            model_name='saleitem',
            name='sale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sale_items', to='app_store.sale'),
        ),
    ]
